/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import aplicacion.FachadaAplicacion;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JTextField;
import pojos.Empleado;
import pojos.Hostelero;
import pojos.Trabajador;

/**
 *
 * @author alumnogreibd
 */
public class VEmpleado extends javax.swing.JFrame {

    FachadaAplicacion fa;
    JFrame padre;

    /**
     * Creates new form VEmpleado
     */
    public VEmpleado(FachadaAplicacion fa, JFrame padre) {
        this.fa = fa;
        this.padre = padre;
        initComponents();
        tablaEmpleados.setModel(new ModeloTablaEmpleado());
        // Desactiva el botón de inserción por defecto
        btnValidar1.setEnabled(false);
        addCamposCompletosListener();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private void addCamposCompletosListener() {
        List<JTextField> listaTextField = new ArrayList();
        listaTextField.add(txDni1);
        listaTextField.add(txNombre1);
        listaTextField.add(txSalario1);
        //listaTextField.add(txaFormacion1);
        listaTextField.add(txNegocio1);

        // Agrega un DocumentListener a cada uno de los campos de texto
        txDni1.getDocument().addDocumentListener(new CamposCompletosListener(btnValidar1, listaTextField));
        txNombre1.getDocument().addDocumentListener(new CamposCompletosListener(btnValidar1, listaTextField));
        txSalario1.getDocument().addDocumentListener(new CamposCompletosListener(btnValidar1, listaTextField));
        txNegocio1.getDocument().addDocumentListener(new CamposCompletosListener(btnValidar1, listaTextField));
    }


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        tablaSector = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txDNI2 = new javax.swing.JTextField();
        txNombre2 = new javax.swing.JTextField();
        txTelefono2 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnBuscar2 = new javax.swing.JButton();
        btnCancelar2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEmpleados = new javax.swing.JTable();
        btnSalir2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnRefrescar3 = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnValidar1 = new javax.swing.JButton();
        btnCancelar1 = new javax.swing.JButton();
        btnSalir1 = new javax.swing.JButton();
        csSector1 = new javax.swing.JComboBox<>();
        txNacimiento1 = new javax.swing.JFormattedTextField();
        labelNacimiento1 = new javax.swing.JLabel();
        labelNombre1 = new javax.swing.JLabel();
        txNombre1 = new javax.swing.JTextField();
        labelDNI1 = new javax.swing.JLabel();
        txDni1 = new javax.swing.JTextField();
        labelDireccion1 = new javax.swing.JLabel();
        txDireccion1 = new javax.swing.JTextField();
        labelSalario1 = new javax.swing.JLabel();
        txSalario1 = new javax.swing.JTextField();
        txTlf1 = new javax.swing.JTextField();
        labelTlf1 = new javax.swing.JLabel();
        txNegocio1 = new javax.swing.JTextField();
        labelNegocio1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txaFormacion1 = new javax.swing.JTextArea();
        labelFormacion1 = new javax.swing.JLabel();
        labelSector1 = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel15.setText("DNI");

        jLabel16.setText("Nombre");

        jLabel17.setText("Teléfono");

        btnBuscar2.setText("Buscar");

        btnCancelar2.setText("Cancelar");

        tablaEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "DNI", "Nombre", "Teléfono", "Sector"
            }
        ));
        jScrollPane1.setViewportView(tablaEmpleados);

        btnSalir2.setText("Volver");
        btnSalir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel15)
                        .addGap(69, 69, 69)
                        .addComponent(jLabel16)
                        .addGap(58, 58, 58)
                        .addComponent(jLabel17)
                        .addGap(0, 100, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSalir2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar2)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txDNI2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(txNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txTelefono2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txDNI2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txTelefono2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar2)
                    .addComponent(btnCancelar2)
                    .addComponent(btnSalir2))
                .addContainerGap())
        );

        tablaSector.addTab("Buscar Empleado", jPanel3);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Sector", "Cantidad de empleados"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        btnRefrescar3.setText("Refrescar");

        btnSalir.setText("Volver");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnSalir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRefrescar3))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefrescar3)
                    .addComponent(btnSalir))
                .addContainerGap())
        );

        tablaSector.addTab("Consultar Sector", jPanel4);

        btnValidar1.setText("Validar");
        btnValidar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidar1ActionPerformed(evt);
            }
        });

        btnCancelar1.setText("Cancelar");

        btnSalir1.setText("Volver");
        btnSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir1ActionPerformed(evt);
            }
        });

        csSector1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Espectáculos", "Atracciones", "Restaurantes", "Hoteles" }));
        csSector1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                csSector1ActionPerformed(evt);
            }
        });

        txNacimiento1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        txNacimiento1.setToolTipText("dd/MM/yyyy");

        labelNacimiento1.setText("Fecha de Nacimiento");

        labelNombre1.setText("Nombre");

        labelDNI1.setText("DNI");

        labelDireccion1.setText("Direccion");

        labelSalario1.setText("Salario");

        labelTlf1.setText("Telefono");

        labelNegocio1.setText("Negocio");

        txaFormacion1.setColumns(20);
        txaFormacion1.setRows(5);
        jScrollPane3.setViewportView(txaFormacion1);

        labelFormacion1.setText("Formacion");

        labelSector1.setText("Sector");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalir1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelNegocio1)
                            .addComponent(labelTlf1))
                        .addGap(190, 190, 190)
                        .addComponent(btnValidar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelDNI1)
                            .addComponent(labelNombre1))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txTlf1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(labelSalario1))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txNegocio1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(labelSector1))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(labelDireccion1))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txDni1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelNacimiento1)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txSalario1, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                .addComponent(txDireccion1)
                                .addComponent(txNacimiento1))
                            .addComponent(csSector1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelFormacion1)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(107, 107, 107))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre1)
                    .addComponent(txNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDireccion1)
                    .addComponent(txDireccion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txDni1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDNI1)
                    .addComponent(labelNacimiento1)
                    .addComponent(txNacimiento1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTlf1)
                    .addComponent(txTlf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSalario1)
                    .addComponent(txSalario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelSector1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelNegocio1)
                        .addComponent(txNegocio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(csSector1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(labelFormacion1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnValidar1)
                    .addComponent(btnCancelar1)
                    .addComponent(btnSalir1))
                .addContainerGap())
        );

        tablaSector.addTab("Alta", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tablaSector)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tablaSector, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tablaSector.getAccessibleContext().setAccessibleName("Alta");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir2ActionPerformed
        padre.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnSalir2ActionPerformed

    private void csSector1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csSector1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_csSector1ActionPerformed

    private void btnValidar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidar1ActionPerformed
        String dni = txDni1.getText();
        String nombre = txNombre1.getText();
        String telefono = txTlf1.getText();
        String strNacimiento = txNacimiento1.getText();
        String negocio = txNegocio1.getText();
        String direccion = txDireccion1.getText();
        String salario = txSalario1.getText();
        String formacion = txaFormacion1.getText();
        if (formacion == null) {
            formacion = "No formado";
        }
        String sector = (String) csSector1.getSelectedItem();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        Date nacimientoDate = null;
        try {
            nacimientoDate = formato.parse(strNacimiento);
        } catch (ParseException e) {
            System.out.println(e.getMessage());
        }
        java.sql.Date nacimientoSQL = new java.sql.Date(nacimientoDate.getTime());
// Creamos un objeto java.util.Date con la fecha actual
        java.util.Date ahoraUtil = new java.util.Date();

// Creamos un objeto java.sql.Date utilizando el valor de milisegundos del objeto java.util.Date
        java.sql.Date ahoraSql = new java.sql.Date(ahoraUtil.getTime());

        Empleado e;
        if (sector == "Restaurante" || sector == "Hotel") {
            e = new Hostelero(dni, nombre, direccion, Double.parseDouble(salario), telefono, ahoraSql, nacimientoSQL, formacion);
        } else {
            e = new Trabajador(dni, nombre, direccion, Double.parseDouble(salario), telefono, ahoraSql, nacimientoSQL, formacion);
        }
        fa.insertarEmpleado(e);
        txDni1.setText("");
        txNombre1.setText("");
        txNacimiento1.setText("");
        txTlf1.setText("");
        txNegocio1.setText("");
        txDireccion1.setText("");
        txSalario1.setText("");
        txaFormacion1.setText("");
    }//GEN-LAST:event_btnValidar1ActionPerformed

    private void btnSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir1ActionPerformed
        padre.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnSalir1ActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        padre.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar2;
    private javax.swing.JButton btnCancelar1;
    private javax.swing.JButton btnCancelar2;
    private javax.swing.JButton btnRefrescar3;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSalir1;
    private javax.swing.JButton btnSalir2;
    private javax.swing.JButton btnValidar1;
    private javax.swing.JComboBox<String> csSector1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel labelDNI1;
    private javax.swing.JLabel labelDireccion1;
    private javax.swing.JLabel labelFormacion1;
    private javax.swing.JLabel labelNacimiento1;
    private javax.swing.JLabel labelNegocio1;
    private javax.swing.JLabel labelNombre1;
    private javax.swing.JLabel labelSalario1;
    private javax.swing.JLabel labelSector1;
    private javax.swing.JLabel labelTlf1;
    private javax.swing.JTable tablaEmpleados;
    private javax.swing.JTabbedPane tablaSector;
    private javax.swing.JTextField txDNI2;
    private javax.swing.JTextField txDireccion1;
    private javax.swing.JTextField txDni1;
    private javax.swing.JFormattedTextField txNacimiento1;
    private javax.swing.JTextField txNegocio1;
    private javax.swing.JTextField txNombre1;
    private javax.swing.JTextField txNombre2;
    private javax.swing.JTextField txSalario1;
    private javax.swing.JTextField txTelefono2;
    private javax.swing.JTextField txTlf1;
    private javax.swing.JTextArea txaFormacion1;
    // End of variables declaration//GEN-END:variables
}
