/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import aplicacion.FachadaAplicacion;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import pojos.Visitante;

/**
 *
 * @author alumnogreibd
 */
public class VVisitantes extends JFrame {

    FachadaAplicacion fa;
    JFrame padre;

    /**
     * Creates new form VVisitantes
     */
    public VVisitantes(FachadaAplicacion fa, JFrame padre) {
        this.fa = fa;
        this.padre = padre;
        initComponents();

        tablaVisitantes.setModel(new ModeloTablaVisitantes());
        tablaVisitantes.setColumnSelectionAllowed(false);
        tablaVisitantes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablaVisitantes.getTableHeader().setReorderingAllowed(false);
        scrollPaneTabla.setViewportView(tablaVisitantes);
        tablaVisitantes.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        // Desactiva el botón de inserción por defecto
        btnInsertar.setEnabled(false);
        addCamposCompletosListener();
    }

    private void addCamposCompletosListener() {
        List<JTextField> listaTextField = new ArrayList();
        listaTextField.add(textFieldDni);
        listaTextField.add(textFieldFechaNac);
        //listaTextField.add(textFieldNacionalidad);
        listaTextField.add(textFieldNombre);
        listaTextField.add(textFieldTlf);
        // Agrega un DocumentListener a cada uno de los campos de texto
        textFieldDni.getDocument().addDocumentListener(new CamposCompletosListener(btnInsertar, listaTextField));
        textFieldFechaNac.getDocument().addDocumentListener(new CamposCompletosListener(btnInsertar, listaTextField));
        //textFieldNacionalidad.getDocument().addDocumentListener(new CamposCompletosListener(btnInsertar, listaTextField));

        textFieldNombre.getDocument().addDocumentListener(new CamposCompletosListener(btnInsertar, listaTextField));

        textFieldTlf.getDocument().addDocumentListener(new CamposCompletosListener(btnInsertar, listaTextField));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        emergenteBusquedas = new javax.swing.JPopupMenu();
        miBorrar = new javax.swing.JMenuItem();
        miAltura = new javax.swing.JMenuItem();
        miAtracciones = new javax.swing.JMenuItem();
        miEspectaculos = new javax.swing.JMenuItem();
        miRestaurantes = new javax.swing.JMenuItem();
        miHoteles = new javax.swing.JMenuItem();
        menuSuperior = new javax.swing.JTabbedPane();
        panelNuevo = new javax.swing.JPanel();
        textFieldDni = new javax.swing.JTextField();
        labelDNI = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        textFieldNombre = new javax.swing.JTextField();
        labelNacionalidad = new javax.swing.JLabel();
        textFieldTlf = new javax.swing.JTextField();
        labelTlf = new javax.swing.JLabel();
        labelAltura = new javax.swing.JLabel();
        sliderAltura = new javax.swing.JSlider();
        labelFechaNac = new javax.swing.JLabel();
        textFieldFechaNac = new javax.swing.JFormattedTextField();
        btnInsertar = new javax.swing.JButton();
        cbNacionalidad = new javax.swing.JComboBox<>();
        panelBuscar = new javax.swing.JPanel();
        textFieldBuscar = new javax.swing.JTextField();
        labelBuscar = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        scrollPaneTabla = new javax.swing.JScrollPane();
        tablaVisitantes = new javax.swing.JTable();
        btnSalir = new javax.swing.JButton();

        miBorrar.setText("Borrar");
        miBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miBorrarActionPerformed(evt);
            }
        });
        emergenteBusquedas.add(miBorrar);

        miAltura.setText("Consultar Atracciones Disponibles por Altura");
        miAltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAlturaActionPerformed(evt);
            }
        });
        emergenteBusquedas.add(miAltura);

        miAtracciones.setText("Consultar Atracciones Visitadas");
        miAtracciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAtraccionesActionPerformed(evt);
            }
        });
        emergenteBusquedas.add(miAtracciones);

        miEspectaculos.setText("Espectaculos Visitadas");
        miEspectaculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEspectaculosActionPerformed(evt);
            }
        });
        emergenteBusquedas.add(miEspectaculos);

        miRestaurantes.setText("Restaurantes Visitadas");
        miRestaurantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRestaurantesActionPerformed(evt);
            }
        });
        emergenteBusquedas.add(miRestaurantes);

        miHoteles.setText("Hoteles Visitadas");
        miHoteles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miHotelesActionPerformed(evt);
            }
        });
        emergenteBusquedas.add(miHoteles);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelDNI.setText("DNI:");

        labelNombre.setText("Nombre:");

        labelNacionalidad.setText("Nacionalidad:");

        labelTlf.setText("Teléfono:");

        labelAltura.setText("Altura:");

        sliderAltura.setMajorTickSpacing(20);
        sliderAltura.setMaximum(250);
        sliderAltura.setMinimum(100);
        sliderAltura.setMinorTickSpacing(5);
        sliderAltura.setPaintLabels(true);
        sliderAltura.setPaintTicks(true);
        sliderAltura.setPaintTrack(false);
        sliderAltura.setSnapToTicks(true);
        sliderAltura.setValue(170);
        sliderAltura.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        labelFechaNac.setText("Fecha de Nacimiento:");

        textFieldFechaNac.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        textFieldFechaNac.setToolTipText("dd/MM/yyyy");
        textFieldFechaNac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldFechaNacActionPerformed(evt);
            }
        });

        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });

        cbNacionalidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Española", "Mexicana", "Argentina", "Colombiana", "Uruguaya", "Chilena", "Venezolana", "Peruana", "Alemana", "Francesa", "Italiana", "Holandesa", "Británica", "Irlandesa", "Sueca", "Noruega", "Dinamarca", "Finlandesa", "Polaca", "Rusa", "Checa", "Griega", "Turca", "China", "Japonesa", "Estadounidense", "Canadiense", "Brasileña", " ", " ", " " }));
        cbNacionalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNacionalidadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelNuevoLayout = new javax.swing.GroupLayout(panelNuevo);
        panelNuevo.setLayout(panelNuevoLayout);
        panelNuevoLayout.setHorizontalGroup(
            panelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNuevoLayout.createSequentialGroup()
                .addGroup(panelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelNuevoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnInsertar))
                    .addGroup(panelNuevoLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(panelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelNuevoLayout.createSequentialGroup()
                                .addComponent(labelDNI)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textFieldDni, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelFechaNac))
                            .addGroup(panelNuevoLayout.createSequentialGroup()
                                .addComponent(labelNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(101, 101, 101)
                                .addComponent(labelTlf))
                            .addGroup(panelNuevoLayout.createSequentialGroup()
                                .addComponent(labelNacionalidad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(117, 117, 117)
                                .addComponent(labelAltura)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sliderAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(textFieldTlf, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(textFieldFechaNac, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        panelNuevoLayout.setVerticalGroup(
            panelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNuevoLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(panelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelFechaNac, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelDNI)
                        .addComponent(textFieldFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textFieldDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addGroup(panelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTlf)
                    .addGroup(panelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelNombre)
                        .addComponent(textFieldTlf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sliderAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNacionalidad)
                    .addComponent(cbNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAltura))
                .addGap(18, 18, 18)
                .addComponent(btnInsertar)
                .addContainerGap())
        );

        menuSuperior.addTab("Nuevo", panelNuevo);

        labelBuscar.setText("Nombre:");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tablaVisitantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "DNI", "Nombre", "Fecha de nacimiento", "Nacionalidad", "Altura", "Telefono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaVisitantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaVisitantesMousePressed(evt);
            }
        });
        scrollPaneTabla.setViewportView(tablaVisitantes);

        javax.swing.GroupLayout panelBuscarLayout = new javax.swing.GroupLayout(panelBuscar);
        panelBuscar.setLayout(panelBuscarLayout);
        panelBuscarLayout.setHorizontalGroup(
            panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPaneTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 848, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelBuscarLayout.createSequentialGroup()
                        .addComponent(labelBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBuscarLayout.setVerticalGroup(
            panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelBuscar)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollPaneTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        labelBuscar.getAccessibleContext().setAccessibleDescription("dni del visitante");

        menuSuperior.addTab("Buscar", panelBuscar);

        btnSalir.setText("Volver");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(menuSuperior)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSalir)
                        .addGap(31, 31, 31))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/* Añadir opcion de borrar al hacer click derecho*/
    private void tablaVisitantesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaVisitantesMousePressed
        // Verificar si se ha hecho clic derecho
        if (SwingUtilities.isRightMouseButton(evt)) {
            // Obtener la fila seleccionada
            int row = tablaVisitantes.rowAtPoint(evt.getPoint());
            if (row >= 0 && row < tablaVisitantes.getRowCount()) {
                // Seleccionar la fila
                tablaVisitantes.setRowSelectionInterval(row, row);
                // Mostrar el menú emergente en la posición del clic derecho
                emergenteBusquedas.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_tablaVisitantesMousePressed

    private void miAlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAlturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miAlturaActionPerformed

    private void miAtraccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAtraccionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miAtraccionesActionPerformed

    private void miRestaurantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRestaurantesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miRestaurantesActionPerformed

    private void miHotelesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miHotelesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miHotelesActionPerformed

    private void miEspectaculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEspectaculosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miEspectaculosActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        buscarVisitantes();

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
        fa.iniciaInterfazUsuario();
        //padre.setVisible(true);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed

        String dni = textFieldDni.getText();
        String nombre = textFieldNombre.getText();
        String nacionalidad = (String) cbNacionalidad.getSelectedItem();//textFieldNacionalidad.getText();
        String telefono = textFieldTlf.getText();
        String strNacimiento = textFieldFechaNac.getText();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        Date nacimientoDate = null;
        try {
            nacimientoDate = formato.parse(strNacimiento);
        } catch (ParseException e) {
            System.out.println(e.getMessage());
        }
        java.sql.Date nacimientoSQL = new java.sql.Date(nacimientoDate.getTime());
        float altura = sliderAltura.getValue() / 100.0f;

        fa.insertarVisitante(new Visitante(dni, nombre, nacionalidad, telefono, nacimientoSQL, altura));
        textFieldDni.setText("");
        textFieldNombre.setText("");
        cbNacionalidad.setSelectedIndex(0);
        textFieldTlf.setText("");
        textFieldFechaNac.setText("");
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void miBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miBorrarActionPerformed
        int selectedRow = tablaVisitantes.getSelectedRow();
        if (selectedRow != -1) { // Si hay al menos una fila seleccionada
            String dni = (String) tablaVisitantes.getValueAt(selectedRow, 0); // Obtenemos el DNI de la fila seleccionada
            // Llamamos a la función que borra el visitante de la base de datos
            fa.borrarVisitante(dni);
            // Eliminamos la fila de la JTable
            ModeloTablaVisitantes model = (ModeloTablaVisitantes) tablaVisitantes.getModel();
            model.removeRow(selectedRow);
        }

    }//GEN-LAST:event_miBorrarActionPerformed

    private void cbNacionalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNacionalidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbNacionalidadActionPerformed

    private void textFieldFechaNacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldFechaNacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldFechaNacActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbNacionalidad;
    private javax.swing.JPopupMenu emergenteBusquedas;
    private javax.swing.JLabel labelAltura;
    private javax.swing.JLabel labelBuscar;
    private javax.swing.JLabel labelDNI;
    private javax.swing.JLabel labelFechaNac;
    private javax.swing.JLabel labelNacionalidad;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelTlf;
    private javax.swing.JTabbedPane menuSuperior;
    private javax.swing.JMenuItem miAltura;
    private javax.swing.JMenuItem miAtracciones;
    private javax.swing.JMenuItem miBorrar;
    private javax.swing.JMenuItem miEspectaculos;
    private javax.swing.JMenuItem miHoteles;
    private javax.swing.JMenuItem miRestaurantes;
    private javax.swing.JPanel panelBuscar;
    private javax.swing.JPanel panelNuevo;
    private javax.swing.JScrollPane scrollPaneTabla;
    private javax.swing.JSlider sliderAltura;
    private javax.swing.JTable tablaVisitantes;
    private javax.swing.JTextField textFieldBuscar;
    private javax.swing.JTextField textFieldDni;
    private javax.swing.JFormattedTextField textFieldFechaNac;
    private javax.swing.JTextField textFieldNombre;
    private javax.swing.JTextField textFieldTlf;
    // End of variables declaration//GEN-END:variables

    public void buscarVisitantes() {
        ModeloTablaVisitantes m;
        String nombre = textFieldBuscar.getText();
        m = (ModeloTablaVisitantes) tablaVisitantes.getModel();

        m.setFilas(fa.obtenerVisitantes(nombre));
        if (m.getRowCount() > 0) {
            tablaVisitantes.setRowSelectionInterval(0, 0);
        }
    }
}
